### ISSUE TITLE
It removes the ability to use Alt-Enter in Dart files

### ISSUE THREAD

**Issue by nerder** [thvardhan/Gradianto#10]
As in title, using the theme i'm not able to user `Alt + Enter` shortcut for code generation.

Hope it will be fixed as soon as possible, i do really enjoy the theme!

Thank you for your awsome work

**Comment by thvardhan** [comment]
Thanks for the report, I'll surely take a look at it asap

**Comment by thvardhan** [comment]
Hi, Are you sure it is the theme that is causing this issue? because I am only changing the colors of the IDE and when I alt enter on dart files with the theme, I do get the auto-completion menu. Can you update to the latest version of whichever JetBrains' IDE you are using and see if that helps?

**Comment by nerder** [comment]
That's interesting because as soon as I deactivate the theme the contextual menu starts appearing again. Let me try to update everything and I'll get back to you asap.
