### ISSUE TITLE
More obvious hint when there is error in code

### ISSUE THREAD

**Issue by tuyu79** [thvardhan/Gradianto#12]
Hi,i am using gradianto in idea,and its a cool theme in my work experience.However,there is something i think is not very friendly to users.The problem is that when there is error in my code,i cant distinguish 
between error and warning,because their  hint color is so close!So,is there some solution to solve the problem or someother workaround?

**Comment by thvardhan** [comment]
Hi thanks for bringing this to my attention. if you are facing this issue then others might be facing it too. I'll take a look and fix it. meanwhile you can go to intellij settings and change color scheme manually.

**Comment by thvardhan** [comment]
Hi I've changed the error color to pink-ish in the new build which looks pretty good. Sorry took me so long thanks to the on going pandemic. The update has been pushed to the repository and will be available as a plugin update in your IDE as soon as JetBrains finish moderating the file.

**Comment by tuyu79** [comment]
Thinks a&nbsp; lot!



---Original---
