### ISSUE TITLE
IDE pugin and Update screen

### ISSUE THREAD

**Issue by tekalenandkumar** [thvardhan/Gradianto#14]
IDE pugin and Update page has issue and text is not clearly visible.

![image](https://user-images.githubusercontent.com/4456951/80785705-cdad4600-8b9e-11ea-974b-3ce044bdcf09.png)

I had to select text to read it.

![image](https://user-images.githubusercontent.com/4456951/80785803-1cf37680-8b9f-11ea-9dd3-d3c42a81c6bf.png)

**Comment by thvardhan** [comment]
Fixed in 3.9 update. Would be available in your IDE as soon as the update is accepted by JetBrains.
