### ISSUE TITLE
3.10 update missing Editor->Color Scheme items

### ISSUE THREAD

**Issue by skj-dev** [thvardhan/Gradianto#16]
After updating to 3.10 via the Plugin update in IntelliJ IDEA all the `Gradianto` entries are gone from the Editor->Color Scheme->Scheme dropdown menu. 

Rolling back to 3.9 restored the list.

**Comment by thvardhan** [comment]
Which version of IntelliJ IDEA are you using?
Using IDEA 2020.1 I can confirm that the color schemes are present

**Comment by skj-dev** [comment]
Sorry, should have included that.

I'm on 2020.1.1

**Comment by skj-dev** [comment]
Okay, so it just requires a restart. Apparently the "hot apply" piece is not playing nice. Apologies for the noise. 😄
