### ISSUE TITLE
What is the font and its corresponding settings as used in the screenshots?

### ISSUE THREAD

**Issue by user19482** [thvardhan/Gradianto#17]
Since the theme didn't end up looking like in the screenshots upon installation, I wanted to know what font is used in the screenshots and if there are any settings corresponding to the font.

**Comment by thvardhan** [comment]
The font used is : JetBrains Mono, I think the size is about 15. line spacing is 1.2. The screenshots were taken on a linux machine so there might be some slight rendering differences if the same is done in windows.
