### ISSUE TITLE
Incompatible with IU-202.4357.23

### ISSUE THREAD

**Issue by doublefx** [thvardhan/Gradianto#18]
Hi,

First I love this plugin, many thanks for your excellent work !!

Unfortunately it is currently incompatible with IU-202.4357.23

With the hope to use it again soon :-)

**Comment by thvardhan** [comment]
Hi, thanks for reaching out. is that an early version?

**Comment by doublefx** [comment]
Yes, the last EAP, until now, despite I'm on that version I never had any issues.

**Comment by thvardhan** [comment]
I've downloaded the EAP and it works fine. Can you tell me exactly what error do you have if any? have you tried reinstalling?
<img width="1102" alt="Screenshot 2020-05-28 at 6 06 45 PM" src="https://user-images.githubusercontent.com/17314986/83142433-1dcfe780-a10e-11ea-9c56-c172a96ee50b.png">

**Comment by doublefx** [comment]
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.4357.23, built on May 27, 2020
IntelliJ IDEA EAP User
Expiration date: June 26, 2020
Runtime version: 11.0.7+10-b912.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: HOCON Converter, String Manipulation, com.alayouni.ansiHighlight, com.dmitryzhelnin.intellij.plugin.gitextensions, com.github.b3er.idea.plugins.arc.browser, com.intellij.ideolog, GrepConsole, SystemProperties, io.codearte.props2yaml, me.vukas.remote-debug, com.jetbrains.plugins.ini4idea, de.netnexus.camelcaseplugin, ideanginx9, net.ashald.envfile, net.seesharpsoft.intellij.plugins.csv, org.intellij.RegexpTester, org.intellij.plugins.hcl, org.jetbrains.plugins.hocon, git-extended-update-index, com.intellij.kubernetes, org.sonarlint.idea, in.1ton.idea.spring.assistant.plugin, com.intellij.plugin.adernov.powershell, org.jetbrains.plugins.vue, com.nvinayshetty.DTOnator, com.intellij.plugins.html.instantEditing, org.intellij.scala, com.weirddev.testme, MetricsReloaded, com.jetbrains.edu, training, org.asciidoctor.intellij.asciidoc

![Capture](https://user-images.githubusercontent.com/1222171/83143332-b2741e80-a0e9-11ea-9018-991ca514253b.PNG)

**Comment by thvardhan** [comment]
It seems that you have already downloaded the plugin for some other version of IntelliJ because it says "disable" on the top right. Can you try uninstalling the theme and then reinstalling from the marketplace? I've seen some other plugins work this way.

**Comment by doublefx** [comment]
I did that for other plugins but it did not work, it did with yours thought :-) I'm happy this great theme is back, thanks !

**Comment by thvardhan** [comment]
That's great! glad the issue is solved
