### ISSUE TITLE
The plugin is not supported in Android Studio 3.4

### ISSUE THREAD

**Issue by marcocadei** [thvardhan/Gradianto#2]
I can't install this plugin in Android Studio 3.4.  
Am i missing or something or it is just not supported?

**Comment by thvardhan** [comment]
According to the update logs,
<img width="548" alt="image" src="https://user-images.githubusercontent.com/17314986/57965977-7ef4a500-7969-11e9-9df6-bc5cab2cc301.png">
so basically, studio 3.4 is intellij idea 2018 edition. The theme plugins only support versions of 2019+.
So I think it is not supported yet.
