### ISSUE TITLE
Horizontal scrollbar is not themed

### ISSUE THREAD

**Issue by bric3** [thvardhan/Gradianto#21]
Excellent theme, the green nature is superb !

I noticed this glitch 👍 
![image](https://user-images.githubusercontent.com/803621/85833453-0843f100-b792-11ea-98ed-f530ee1bfad4.png)

Gradianto : 4.0

```
IntelliJ IDEA 2020.1.3 Preview (Ultimate Edition)
Build #IU-201.8538.6, built on June 24, 2020
Licensed to Comuto SA / Brice Dutheil
Subscription is active until January 22, 2021
Runtime version: 11.0.7+10-b765.64 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.github.b3er.idea.plugins.arc.browser, com.github.weisj.darkmode, Lua, GrepConsole, JOL, Lombook Plugin, com.intellij.bigdecimal-folding, org.jetbrains.plugins.spotbugs, com.mallowigi.idea, com.thvardhan.gradianto, intellij-clock, jd-intellij, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.file-preview, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, com.intellij.kubernetes, Pythonid, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.jetbrains.packagesearch.intellij-plugin, org.asciidoctor.intellij.asciidoc, org.toml.lang, org.rust.lang
```

**Comment by thvardhan** [comment]
Hi, thanks for the report I'll check it asap :)

**Comment by thvardhan** [comment]
Looking at the properties I do not see any value to change the color of horizontal scrollbar. I am open to suggestions but I think it is not possible on Mac right now. if anyone can refer me to another theme that properly colors the scrollbar then I can check how they do it and implement the same.

**Comment by bric3** [comment]
I know that Solarized theme, can do it, yet I'm not sure what is the actual difference. They seem to declare the colors in the xml file as well.
https://github.com/4lex4/intellij-platform-solarized

**Comment by thvardhan** [comment]
Thanks! I've found the properties required to theme the horizontal scrollbar. The new update along with some other fixes will be updated on the JetBrains Store in a few days.
