### ISSUE TITLE
The green one does not show.

### ISSUE THREAD

**Issue by xmarkclx** [thvardhan/Gradianto#22]
Kind of odd, since it is the one shown on the marketplace.

**Comment by thvardhan** [comment]
Hi, can you tell me the steps involved? if it's not working can you try reinstalling the theme and restarting the IDE? also, some more details such as your IDE and OS would be handy :)

**Comment by thvardhan** [comment]
I am pretty sure that this was related to #23 because of not having proper version while the build was taking place. Thanks for the report it's now fixed.
