### ISSUE TITLE
WebStorm 2020.2 incompatible with the Gradianto plugin

### ISSUE THREAD

**Issue by wessel-s2** [thvardhan/Gradianto#23]
WebStorm released version 2020.2 yesterday, and it seems that the Gradianto plugin is incompatible:
`Plugin Error: Plugin "Gradianto" is incompatible (until build 201.SNAPSHOT < WS-202.6397.88).`

The Gradianto plugin still works fine in other Jetbrains apps I'm using (Rider 2020.1.4, DataGrip 2020.1.5)

**Comment by thvardhan** [comment]
Hi, that should not be the case have you tried #18 ? can you let me know if that works otherwise I'll check it in a bit

**Comment by wessel-s2** [comment]
Thank you for the quick reply! I had the incompatibility issue on 2 different machines. 
Reinstalling the plugin seems to have solved the problem, but now I don't see my beloved Nature Green theme in the themes dropdown.
![image](https://user-images.githubusercontent.com/22399353/88663177-735b4d00-d0db-11ea-9eca-e7c3284ffe1e.png)

**Comment by thvardhan** [comment]
oh? can you check which version of the plugin you are using?

**Comment by wessel-s2** [comment]
I just checked and I have v3.9 installed.
![image](https://user-images.githubusercontent.com/22399353/88663896-8fabb980-d0dc-11ea-89f2-0b3deb81e504.png)

And now that you mention it, in the other apps I have v4, but in WebStorm it doesn't indicate that the plugin is outdated for some reason
![image](https://user-images.githubusercontent.com/22399353/88664106-d7324580-d0dc-11ea-8045-19ba6f1c7653.png)

**Comment by thvardhan** [comment]
hm well that's new, I am going install webstorm 2020.2 right now and check what's happening here

**Comment by wessel-s2** [comment]
It is by no means a priority for me personally, but thank you for going out of your way to investigate. And thanks for the amazing themes in general! :)

**Comment by thvardhan** [comment]
Hey, thanks for the report it seems there was a serious substitution going on in the compatibilty version. I did not realize it as it was happening during the building process that restricted the plugin to 2020.1.x only. I've removed the substituiton and it is now listed as compatible. I am uploading a release here on GitHub that you can download while the JetBrains team approve my plugin.
Thanks :D
