### ISSUE TITLE
Nature Green not in 2020.2

### ISSUE THREAD

**Issue by dejl** [thvardhan/Gradianto#24]
Nature Green theme seems to be missing from 2020.2 release?

**Comment by thvardhan** [comment]
Hi, the issue has been fixed and should've already came as an update in your IDE. it is a duplicate to #23 . Thanks for the report.

**Comment by thvardhan** [comment]
can you confirm if this issue still persists? Please let me know if it still exists so I will take a look at it.

**Comment by dejl** [comment]
It is fixed, thanks :)
