### ISSUE TITLE
Some popup have items that are a a difficult to read contrast

### ISSUE THREAD

**Issue by bric3** [thvardhan/Gradianto#28]
How to reporduce:

1. Type a something that the spell check don't like
2. Hover the underline text with the mouse

<img width="587" alt="image" src="https://user-images.githubusercontent.com/803621/96301559-ac7acd80-0ff7-11eb-82b8-a16667f18fe5.png">

Notice the gray items.

I'm not sure how color should adjusted, I see two ways at this time. 
1. reduce the brightness of the popup background
2. or make these items less dark gray

**Comment by thvardhan** [comment]
Hi, thanks again for opening an issue 👍 I'll check it in a bit probably because of wrong color inheritance from darcula theme.

**Comment by bric3** [comment]
Hi, well I'm just reporting, this is more easy than you doing the job ;)

Thnaks for your work !

**Comment by thvardhan** [comment]
Note to self : Issue persisting in other themes as well!

**Comment by thvardhan** [comment]
Hi, it seems the issue is fixed in a new version of Gradianto that I am about to push in a few mins (version 4.4) I am not able to reproduce it anymore and I am not certain what fixed it as I was messing around with other color values. Once you get a chance please let me know if it still persists.

**Comment by bric3** [comment]
Hi,

For me the issue still persists (with Gradianto Nature Green), although the contrast is a bit better with the other variant, the labels are still gray and difficult to read.

**Comment by thvardhan** [comment]
I was able to produce it once but now it just doesnt work, can you share me an example file with typo and version of intellij?

**Comment by bric3** [comment]
@thvardhan Hi, I jiust retested on IntelliJ 2021.1, and the issue is gone indeed, the tootip backgroud color is dark, and as such the gray text is readable.

Thanks for looking into it.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/803621/119631397-2685f700-be10-11eb-87e9-03c78c13c198.png">
