### ISSUE TITLE
Narrow scroll bars have poor contrast, especially in Deep Ocean

### ISSUE THREAD

**Issue by cypherdare** [thvardhan/Gradianto#33]
Narrow scroll bars are in the Settings window and side panels. It is not so bad in most side panels, but it is very hard to see in the Settings window, and more importantly, the panels in the various Android Studio XML editors because they use the darker shade of blue for the background. I keep having to squint and lean close to the screen to find the scroll bar.

![image](https://user-images.githubusercontent.com/1843131/101407438-e99d6680-38a8-11eb-8022-976fa36c2946.png)

![image](https://user-images.githubusercontent.com/1843131/101407661-308b5c00-38a9-11eb-8aab-2b6a927012f0.png)

**Comment by thvardhan** [comment]
Hi, sorry for the late response, the issue somehow slipped by my notification system. anyways I'll take a look at it asap

**Comment by thvardhan** [comment]
fixed in 4.4 (releasing in a bit)

**Comment by cypherdare** [comment]
Thank you!
