### ISSUE TITLE
Actual theme not changing

### ISSUE THREAD

**Issue by SwordOfSouls** [thvardhan/Gradianto#35]
I am using the deep ocean theme but the editor theme changes but the main intellij theme doesn't change
This is the link:
https://imgur.com/a/kSt1Ekn

**Comment by thvardhan** [comment]
Hi, it seems your color scheme did not apply properly. you can apply it manually from editor tab. select gradianto deep ocean there and this should fix. let me know if it does not.<img width="966" alt="Screenshot 2021-05-28 at 8 11 40 AM" src="https://user-images.githubusercontent.com/17314986/119921842-58bc6380-bf8c-11eb-9430-4704bc56db32.png">

**Comment by thvardhan** [comment]
also if the issue persists, I would say restart your ide and switch the theme to any other version and change back to deep ocean it should do the trick.

**Comment by SwordOfSouls** [comment]
Thanks for the help that works! Sorry for the bother, I'm switching over to Intellij after a long time of using Eclipse so thanks for the help!

**Comment by thvardhan** [comment]
:D glad could help
