### ISSUE TITLE
Use transparent colors for drag & dock editors

### ISSUE THREAD

**Issue by bric3** [thvardhan/Gradianto#39]
Feature https://www.jetbrains.com/idea/guide/tips/drag-and-dock/

IntelliJ light and Darcula have a transparent overlay when dragging editors, but when gradianto is used the overlay is opaque.

![Gradianto editor drag](https://user-images.githubusercontent.com/803621/178752431-e6c363cc-ca82-4ab8-a8a5-76a495a5aad1.png)

Versus Darcula

![Darcula editor drag](https://user-images.githubusercontent.com/803621/178752825-155282d8-8e07-4d9d-a8f4-cc09e61bf27b.png)

**Comment by thvardhan** [comment]
Fixed in 4.6 (will be live as soon as JetBrains approve the build) Thank you for reporting the issue.
