### ISSUE TITLE
Color "Quick documentation"

### ISSUE THREAD

**Issue by Paracells** [thvardhan/Gradianto#4]
Hello. Bug with hint quick documentation. Standard color tip window

Gradianto Deep Ocean

![5](https://user-images.githubusercontent.com/575811/60751524-44010c00-9fbf-11e9-861b-ff02adafc7ab.png)

and it's ok at

Gradianto Midnight Blue

![4](https://user-images.githubusercontent.com/575811/60751529-58450900-9fbf-11e9-833e-f622eb025f12.png)

**Comment by thvardhan** [comment]
Hi, thanks for reporting this. I am on vacation right now and dont have access to computer. I will fix this issue as soon as I am back.

**Comment by thvardhan** [comment]
Hi there, Sorry for the delay. I have just fixed the issue and pushed the new update to JetBrains repository. The update is now being "verified" by JetBrains then it should go live in a day or two. keep an eye out for that :D
