### ISSUE TITLE
v5.0， blue background color on the git tag 

### ISSUE THREAD

**Issue by proper128** [thvardhan/Gradianto#44]
There is a blue background color on the git tag. A problem with 【git tag】 display

IDEA version：IntelliJ IDEA 2021.3.2 (Ultimate Edition) Build #IU-213.6777.52

**Comment by thvardhan** [comment]
Hello, can you please confirm are you referring to this git tag? 
<img width="90" alt="image" src="https://user-images.githubusercontent.com/17314986/220233511-7f6ac906-6617-4c84-bb21-440e49251cb0.png">

**Comment by proper128** [comment]
Right. 发自我的 iPhone在 2023年2月21日，10:39，thvardhan ***@***.***> 写道：﻿
Hello, can you please confirm are you referring to this git tag?

**Comment by thvardhan** [comment]
Thank you for reporting this issue. I've updated the icon to look slightly more blended in the next version
