### ISSUE TITLE
Deep Ocean - git and highlight current branch

### ISSUE THREAD

**Issue by targzeta** [thvardhan/Gradianto#45]
As you can see, the Deep Ocean theme seems to be leaking this feature:
![screenshot_20230220_163820](https://user-images.githubusercontent.com/2431105/220152601-48c0eaab-71c4-4883-8652-3f2ddbcfbcb0.jpg)

Emanuele

**Comment by thvardhan** [comment]
Hello, could you please elaborate more on the issue? What do you mean exactly by leaking?

**Comment by targzeta** [comment]
Hi,
when we view the graph of all branches, this option highlights the commits of the current branch. The Midnight Blue theme works fine, for example, as you can see here:
![screenshot_20230221_131320](https://user-images.githubusercontent.com/2431105/220342868-d3befc9f-916b-4e98-89d7-720650e86d1a.jpg)
I'm currently on the develop branch. I see also the commits on the release branch, but the commits on the develop branch are highlighted.

Best regards,
Emanuele

**Comment by thvardhan** [comment]
Thank you so much for informing this issue! I use this git window all the time and thought there was something odd about it but did not think of highlights. it will be fixed in the next version.
