### ISSUE TITLE
Memory indicator is not colored properly

### ISSUE THREAD

**Issue by bric3** [thvardhan/Gradianto#46]
Enabled the memory indicator and it seems the gauge colors are not handled.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/803621/220754116-fcf16c3a-ce8a-4ea6-afc4-f2cc152286a2.png">

**Comment by thvardhan** [comment]
Thank you so much for reporting this! it has been fixed and a new version is on its way~

P.S. thanks for continued support :)

**Comment by bric3** [comment]
I'd rather thank you
