### ISSUE TITLE
Question: Customizing UI Colors

### ISSUE THREAD

**Issue by CANBAAA** [thvardhan/Gradianto#47]
**I noticed that the UI colors above should be dark when the window is inactive and the theme is dark, but it seems that you have customized these colors. Could you please explain which option is responsible for these color customizations?**

As shown in my picture, when my window is not in active state, the color on top changes to the light theme color.
![201](https://user-images.githubusercontent.com/39176450/224555521-348e1551-53b7-463d-a95b-2e6cc5bf9399.jpg)
Gradianto Nature Green and Gradianto_Nature_Green_new.theme.json
![202](https://user-images.githubusercontent.com/39176450/224555775-45416bd7-9dd2-47ea-8072-e793bb34ad28.jpg)
![203](https://user-images.githubusercontent.com/39176450/224555894-4d51c135-ab04-4e89-91fa-cd32e5ae094f.jpg)

**Comment by thvardhan** [comment]
Hello, sorry for delayed response, totally missed the issue. This is the property you are looking for :
<img width="340" alt="image" src="https://github.com/thvardhan/Gradianto/assets/17314986/800baa5e-6255-44cd-a741-460a32ecc24a">
