### ISSUE TITLE
Review issue

### ISSUE THREAD

**Issue by thvardhan** [thvardhan/Gradianto#48]
Hello my friend! I address to you again... Some flattering words: you have the best plugin!

And now for the problem: I really like the theme "newui nature green", but I stopped using it because it doesn't show well when the text is highlighted. For example in the theme "newui deep ocean" highlighted text can be seen well. If you have time, please do something about it.

Another nyuansom noticed if I open two projects on macos (by selecting in different windows, in the idea is the same window, but in different tabs), so the active project (its tab), highlighted in gray (I think it is the native color ide jb). I hope you understand what I'm talking about )).

Thanks!

**Comment by jdit7c1** [comment]
Hi, I was writing to you ))
Here are screenshots to make it clearer what I was talking about.
In the blue color theme - the selection of text looks fine, it is not lost against the background of the rest.

And on the green color theme - the text highlighting is barely visible, it seems to be mixed in the code is really very hard to see.

I also attached a screenshot of the grayed out tabs.
I am using macos.
Sorry for my English ))


<img width="982" alt="2023-07-04 в 12 19 11" src="https://github.com/thvardhan/Gradianto/assets/29520345/6d7b3f7e-cbbd-4aa8-8bf0-773b9a487ae0">
<img width="982" alt="2023-07-04 в 12 20 32" src="https://github.com/thvardhan/Gradianto/assets/29520345/6591e340-403a-4758-ac3a-fe3160a7b1f7">
<img width="1798" alt="2023-07-04 в 12 23 27" src="https://github.com/thvardhan/Gradianto/assets/29520345/1f36f973-d386-49cd-98f7-7649a0b5c191">

**Comment by thvardhan** [comment]
Thank you for detailing the issue, I've fixed the color highlighting, I am looking to get this multi-tab thing can you tell me how do you open projects like this? in multiple tabs? I do not have access to mac currently but I believe it should be same on linux/windows.

**Comment by jdit7c1** [comment]
about tabs:
I couldn't open in tabs on windows os, and I don't think I can on linux either...
I am using a macbook pro 14 (2023), what do I do to open projects like this:
1. open any project.
2. open another project (without closing the first one).
3. ide will give me how to open the second project (in a new window or in an open project), I choose in a new window and that's how I opened it.
It seems to me that this is only on a macbook with a small diagonal.
In general, the logic is a bit lost, I think that the new window is another ide window, not a tab...

If it doesn't work, that's fine, let it be as it is.
If you want I can give you remote access to my macbook?
I can't talk with my voice as I don't speak en language)

**Comment by thvardhan** [comment]
Thank you again for the details. Yeah, it does seem like a mac only feature. I think debugging it will take time so it's better I arrange a Mac device as remote will be time-consuming for both. Really appreciate it though.

Can you let me know if you face the same issue when using the native high contrast / dark / white theme? The color schemes for these themes are open sourced and could help me debug the issue if you are not facing this issue in other themes ( that is, other themes are properly coloring this window/tab of Mac)

**Comment by thvardhan** [comment]
I'll check if I can get this issue fixed in a few days otherwise I'll just make an update which fixes the highlight color

**Comment by jdit7c1** [comment]
I do not use other themes, only yours, but I took screenshots for you (I restarted the development environment every time):
darkula
<img width="1798" alt="darkula" src="https://github.com/thvardhan/Gradianto/assets/29520345/e68dbfb0-3daf-46ed-93b5-afe43e8331eb">


intelliJ light
<img width="1798" alt="intelliJ light" src="https://github.com/thvardhan/Gradianto/assets/29520345/44412a2a-0cb5-4aab-92a0-939cf0ed494d">


dark
<img width="1798" alt="dark" src="https://github.com/thvardhan/Gradianto/assets/29520345/18b89b53-d50b-422d-aa41-39a0ee541341">


light
<img width="1798" alt="light" src="https://github.com/thvardhan/Gradianto/assets/29520345/c2520275-ae44-4bfc-b18a-12e3031aefe1">


high contrast
<img width="1798" alt="high contrast" src="https://github.com/thvardhan/Gradianto/assets/29520345/bd54c18c-f613-4a16-9ffa-25f777eaf6bc">


I think the best look in you intelliJ light, there thought about it apparently.

**Comment by thvardhan** [comment]
Hmm yeah, it does look theme controllable, let me see if I can figure out the property. Thanks

**Comment by thvardhan** [comment]
Hello, I've done some changes and published a version 5.2 to github releases. its currently neither official nor I've submitted to jetbrains. if you get some time to download the .jar file and test if that fixes both of the above issues, I'll submit it to jetbrains as an official update

**Comment by jdit7c1** [comment]
Hi!
I downloaded and installed it.
1. The text selection is much better now.
2. When the project is in clutches, it's bad here )))
I took screenshots.

The active project - the tab is grayed out.
Not active - tab is grayed out.
When I put the mouse cursor on the inactive project - tab black.

You changed the color but not there ))

<img width="1296" alt="2023-07-05 в 11 54 28" src="https://github.com/thvardhan/Gradianto/assets/29520345/8e5e5cf3-1e0c-448c-ba82-dde424133682">
<img width="1300" alt="2023-07-05 в 11 55 07" src="https://github.com/thvardhan/Gradianto/assets/29520345/7a93068b-9aed-424d-a299-b372d1e6bb5a">

**Comment by thvardhan** [comment]
hm ok so the project tab stays the same I believe. alright. thank you! let me figure out something

**Comment by thvardhan** [comment]
Hi, updated the plugin to v5.3, should work this time but the thing is IF the colors will look good or not. feedback is appreciated :) once you let me know I'll send the plugin for update.

**Comment by jdit7c1** [comment]
I updated.
Here are the screenshots

right - the active project. looks good (maybe the tone of color to pick up, here you see for yourself, I'm not a designer). =)
<img width="932" alt="2023-07-05 в 14 12 43" src="https://github.com/thvardhan/Gradianto/assets/29520345/907eb28a-558c-416d-bb7c-355e10b4ffd8">


the second screenshot on the right is the active project, and on the left hovered the mouse over the inactive project (I do not know about you, but I do not like the color, maybe do not need to change the color).
<img width="840" alt="2023-07-05 в 14 13 00" src="https://github.com/thvardhan/Gradianto/assets/29520345/f725eb27-561a-483c-bb80-921c952d0d79">

**Comment by thvardhan** [comment]
Hm... active project looks a little too light I guess, hover seems ok from the image. I'll see to change the colors if needed

**Comment by thvardhan** [comment]
Thank you for all the testing, really appreciate it :)

**Comment by thvardhan** [comment]
sent for update :)

**Comment by jdit7c1** [comment]
Hello! ))
new screenshots from me:
ocean theme...
missing class name in selected project tab (IMPORTANT open class - not changed after commit).
three screenshots for example:
table db.
db console.
Some class (not changed after commit).
<img width="1028" alt="Снимок экрана 2023-07-11 в 10 51 43" src="https://github.com/thvardhan/Gradianto/assets/29520345/651a3d3b-5ac0-47cf-81f6-52b0efe52fb1">
<img width="1028" alt="Снимок экрана 2023-07-11 в 10 51 57" src="https://github.com/thvardhan/Gradianto/assets/29520345/1845d496-d68c-471b-a4e5-99daa0c52eaf">
<img width="1028" alt="Снимок экрана 2023-07-11 в 10 52 06" src="https://github.com/thvardhan/Gradianto/assets/29520345/b5b9ea78-ad48-4ed0-abf2-bff7a3058ed9">


And here is a screenshot where the class is changed and the class name is displayed correctly (the last tab on the right).
<img width="1028" alt="Снимок экрана 2023-07-11 в 11 22 54" src="https://github.com/thvardhan/Gradianto/assets/29520345/289ca8ea-d1e9-4535-aa8a-8f1b1cb533ba">


The next defect is that no matter what gradianto theme is (I checked on green and ocean):
here is the default gray color when hovering over the project.
<img width="1359" alt="Снимок экрана 2023-07-11 в 10 59 22" src="https://github.com/thvardhan/Gradianto/assets/29520345/5fe2da2f-c980-4e99-80ca-76b5e54f9201">
