### ISSUE TITLE
Fuchsia non discernable colors for hovered link and selected / inactive (in tree for example)

### ISSUE THREAD

**Issue by bric3** [thvardhan/Gradianto#49]
Here's example of links that are hovered

* Hovered links
  <img width="346" alt="Editor, inspection widget" src="https://github.com/thvardhan/Gradianto/assets/803621/8aeb370e-6c14-45be-b47b-3df3209b0edf">
  <img width="113" alt="Some other plugin link" src="https://github.com/thvardhan/Gradianto/assets/803621/76197c34-3460-4a9c-a1a0-f2d1e8329042">

* Unfocused/inactive Tree selection. In the below screenshot, the first node is selected, the other isn't
  <img width="100%" alt="Screenshot 2023-08-31 at 15 42 15" src="https://github.com/thvardhan/Gradianto/assets/803621/8e3bf339-d1dd-4fe4-b598-1afc2d2226db">

**Comment by thvardhan** [comment]
ooof yeah that's bad let me check this real quick

**Comment by thvardhan** [comment]
ok this is fixed in the new version, will be live in a few days

**Comment by bric3** [comment]
Thank you!
