### ISSUE TITLE
Flat buttons

### ISSUE THREAD

**Issue by jkroepke** [thvardhan/Gradianto#5]
Like on the Darcula theme can you made the buttons flat?

Darcula Flat Button:
![image](https://user-images.githubusercontent.com/1560587/62429282-21245d80-b70d-11e9-913e-2a1a10b0e1ae.png)

Current Gradianto Button:
![image](https://user-images.githubusercontent.com/1560587/62429286-2bdef280-b70d-11e9-8321-d3c1d3b613a3.png)

**Comment by thvardhan** [comment]
it's been done, it will show up as the update on JetBrains in a few days.
