### ISSUE TITLE
[NEWUI] Deep Ocean theme broken - editor window is light on macOS

### ISSUE THREAD

**Issue by Anettwax** [thvardhan/Gradianto#50]
Not sure if macOS specific

Theme: [NEWUI] Gradianto Deep Ocean
IDE: PyCharm 2023.2.1 (using New UI)
OS: macOS Ventura 13.5.2

Theme is broken as seen in screenshot
Non-New UI theme works as intended
![image](https://github.com/thvardhan/Gradianto/assets/97183670/91b4068c-9c79-45f6-856e-4c64ae661ae6)

**Comment by thvardhan** [comment]
That's weird, can you go to settings and select the  theme from drop-down there? The settings popup not the one on top right. I think the editor scheme is set to default in your case while the entire ui is set to deep ocean. I'll have to investigate more on this as I don't have access to Mac currently.

**Comment by ElNovi** [comment]
I have the same error after updating to 5.4 - it does this only to the theme i was already using (Midnight Blue), if i switch to other like Ocean Blue it looks fine, but when i switch back to Midnight Blue source theme is white again. Observed in Goland &  IntelliJ Idea Ultimate after update to 5.4

Using Windows 11, New UI.

![image](https://github.com/thvardhan/Gradianto/assets/14199592/1e0dec04-8831-4028-9cc1-fa5e6e1d7caf)

**Comment by Nyfaria** [comment]
> That's weird, can you go to settings and select the theme from drop-down there? The settings popup not the one on top right. I think the editor scheme is set to default in your case while the entire ui is set to deep ocean. I'll have to investigate more on this as I don't have access to Mac currently.

this is the second update this has happened to me on, BUT this is the fix.

**Comment by ElNovi** [comment]
Uninstalling Gradianto and installing it again solved the problem for me.

**Comment by ElNovi** [comment]
Ohhh i see it now ...

After update it switches the theme to the non NEWUI version. That's why it is not working as intended. After switching it to the NEWUI version it works fine.

![image](https://github.com/thvardhan/Gradianto/assets/14199592/6af71bb8-93f3-479c-8289-513e6696e590)

**Comment by jbats3108** [comment]
I have the inverse problem -> using [NEWUI] Midnight Blue makes terminal and editor panels light, but non-[NEWUI] does not. Midnight Blue appears to be the only one I have the issue with, [NEWUI] or not.

I am using the new UI.

```
PhpStorm 2023.2.2
Build #PS-232.9921.55, built on September 15, 2023

Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 7632M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.thvardhan.gradianto (5.4)
    String Manipulation (9.11.3)
    monokai-pro (1.10)
    atom-one (1.5.1)
    com.4lex4.intellij.solarized (2.4.0)
    github.cweijan.test-theme (1.6)
    com.jetbrains.darkPurpleTheme (1.3)
    com.markskelton.one-dark-theme (5.8.0)
    com.stepsize.tech-debt-reporter (1.53.13-211+)
    Gitflow-Fix (0.7.13)
    com.tylerthrailkill.intellij.solarized (3.0.0)
    com.intellij.ideolog (222.1.0.0)
    com.atlassian.bitbucket.references (2022.1.242)
    com.mallowigi (93.1.0)
    ru.adelf.idea.dotenv (2023.2)
    org.sonarlint.idea (9.0.0.75308)
    com.majera.intellij.codereview.bitbucket (2023.3.4.232)
    izhangzhihao.rainbow.brackets (2023.3.4)

```

**Comment by rikertothebridge** [comment]
Similar issue for me : Webstorm, New UI, Windows 10.

Update to 5.4 has now set my terminal window to white for [NEWUI Gradianto Nature Green]. Other [NEWUI] themes seem to colour the terminal background correctly.

![image](https://github.com/thvardhan/Gradianto/assets/19628689/a56c0b7b-787d-4f94-986d-e69e9dd54bdd)

**Comment by thvardhan** [comment]
Hi @rikertothebridge 
can confirm it works fine for all themes including green (in v5.4)
<img width="1200" alt="image" src="https://github.com/thvardhan/Gradianto/assets/17314986/2cc1471f-c6b0-4ab0-bd6d-82205f8be929">
Can you check if proper theme is selected in the color scheme section?
<img width="485" alt="image" src="https://github.com/thvardhan/Gradianto/assets/17314986/ec6d3df0-2445-4568-8d1b-37678132da36">
same for console colors.
@jbats3108 mid night blue seems fine as well, can you confirm the color scheme?

**Comment by thvardhan** [comment]
It appears when changing themes or after an update sometimes the IDE sets a different overall theme from color scheme which may be the reason for this issue.

**Comment by rikertothebridge** [comment]
> Hi @rikertothebridge can confirm it works fine for all themes including green (in v5.4) <img alt="image" width="1200" src="https://user-images.githubusercontent.com/17314986/269382069-2cc1471f-c6b0-4ab0-bd6d-82205f8be929.png"> Can you check if proper theme is selected in the color scheme section? <img alt="image" width="485" src="https://user-images.githubusercontent.com/17314986/269382418-ec6d3df0-2445-4568-8d1b-37678132da36.png"> same for console colors. @jbats3108 mid night blue seems fine as well, can you confirm the color scheme?


> Hi @rikertothebridge can confirm it works fine for all themes including green (in v5.4) <img alt="image" width="1200" src="https://user-images.githubusercontent.com/17314986/269382069-2cc1471f-c6b0-4ab0-bd6d-82205f8be929.png"> Can you check if proper theme is selected in the color scheme section? <img alt="image" width="485" src="https://user-images.githubusercontent.com/17314986/269382418-ec6d3df0-2445-4568-8d1b-37678132da36.png"> same for console colors. @jbats3108 mid night blue seems fine as well, can you confirm the color scheme?

Thanks for the quick reply @thvardhan - I can confirm that it was NOT set up correctly in the 'color scheme' section. Once I changed that to the right setting my terminal looks as I expect again.

**Comment by jbats3108** [comment]
@thvardhan Can confirm the same issue - Editor theme was being set separately. I've set Editor theme to `Gradianto Midnight Blue New` and all is well!

Thanks for the quick response!

**Comment by marchrius** [comment]
Same problem on PopOS! (Ubuntu 22.04).

Solved with changing the Color scheme

**Comment by Anettwax** [comment]
> > Hi @rikertothebridge can confirm it works fine for all themes including green (in v5.4) <img alt="image" width="1200" src="https://user-images.githubusercontent.com/17314986/269382069-2cc1471f-c6b0-4ab0-bd6d-82205f8be929.png"> Can you check if proper theme is selected in the color scheme section? <img alt="image" width="485" src="https://user-images.githubusercontent.com/17314986/269382418-ec6d3df0-2445-4568-8d1b-37678132da36.png"> same for console colors. @jbats3108 mid night blue seems fine as well, can you confirm the color scheme?
> 
> > Hi @rikertothebridge can confirm it works fine for all themes including green (in v5.4) <img alt="image" width="1200" src="https://user-images.githubusercontent.com/17314986/269382069-2cc1471f-c6b0-4ab0-bd6d-82205f8be929.png"> Can you check if proper theme is selected in the color scheme section? <img alt="image" width="485" src="https://user-images.githubusercontent.com/17314986/269382418-ec6d3df0-2445-4568-8d1b-37678132da36.png"> same for console colors. @jbats3108 mid night blue seems fine as well, can you confirm the color scheme?
> 
> Thanks for the quick reply @thvardhan - I can confirm that it was NOT set up correctly in the 'color scheme' section. Once I changed that to the right setting my terminal looks as I expect again.

I also confirm that this approach solves the issue for the editor so this seems more like IDE Issue.

**Comment by elikso** [comment]
And again: Gradianto is updated to 5.5, the same problem returns. Solution is the same: you need to manually change editor color scheme
