### ISSUE TITLE
editor color incorrect

### ISSUE THREAD

**Issue by dgqypl** [thvardhan/Gradianto#56]
Version: 5.5
IDE: GoLand 2023.2.4

In the "[NEWUI] Gradianto Nature Green" theme, the editor color is not green, see the picture:

<img width="1675" alt="企业微信20231101-103357@2x" src="https://github.com/thvardhan/Gradianto/assets/25171658/2ec6fe0e-eb21-4abf-b6ce-36f538422c56">

Even through I uninstall and reinstall GoLand and the problem exists. What's that reason?

**Comment by thvardhan** [comment]
Hello, thanks for the report. Please refer to #50. Let me know if that fixes the issue

**Comment by dgqypl** [comment]
> Hello, thanks for the report. Please refer to #50. Let me know if that fixes the issue

it fixed the issue, thx.
