### ISSUE TITLE
In new version, [NEWUI] Gradianto Nature Green has white editor panes

### ISSUE THREAD

**Issue by markmuday** [thvardhan/Gradianto#57]
Just updated my plugin to v 5.5, and now have white editor panes with Gradianto Nature Green.
![Screenshot 2023-11-01 at 8 02 39 PM](https://github.com/thvardhan/Gradianto/assets/120207403/eb5ab650-2766-4097-8ecc-aede75c85302)

**Comment by thvardhan** [comment]
Hello, please refer to #50

**Comment by markmuday** [comment]
duplicate of #50
