### ISSUE TITLE
"Nature Green" light background  for editor and console

### ISSUE THREAD

**Issue by ZYZ64738** [thvardhan/Gradianto#58]
Since the last update to 5.5 the Sub-Themes "Gradianto Natural Green and [NEWUI] Gradianto Natural Green" show a light (grey) background-color for the editor and the Terminal (I have not checked all views which phpstorm offers. Maybe there are more "light-backgrounds" somewhere, which I have not checked out)

![image](https://github.com/thvardhan/Gradianto/assets/9817678/1cbff625-892f-4fc0-bf6c-be0260842cda)

Before it was dark like the other Sub-themes.

**Comment by thvardhan** [comment]
Hello, please refer to #50

**Comment by ZYZ64738** [comment]
Hi,

finally I could fix it by re-setting the Editor -> Color Scheme 

![image](https://github.com/thvardhan/Gradianto/assets/9817678/2b2f6020-b882-44c8-aa3e-6f77470a2be3)

Everything is fine again now - thank you for this great eye-friendly theme  :pray:
