### ISSUE TITLE
when using [NEWUI]Gradianto Nature Green theme in IDEA, the code edit window's backgroud corlor is white  

### ISSUE THREAD

**Issue by geek-chen** [thvardhan/Gradianto#59]
i am using [NEWUI]Gradianto Nature Green theme, the code edit window's backgroud corlor is white, while other jetbrains product（goLand）do not have this problem 
![image](https://github.com/thvardhan/Gradianto/assets/71498935/007d8da4-9410-445b-bb75-8b6b3407ee70)
![image](https://github.com/thvardhan/Gradianto/assets/71498935/f6671aec-f693-43fd-8e2c-962b3c25639f)

**Comment by thvardhan** [comment]
Hi, please refer to #50

**Comment by geek-chen** [comment]
> Hi, please refer to #50

Thanks for your quick response! the problem has been solved
