### ISSUE TITLE
Search popup, minor adjustment [thats driving me nuts!]

### ISSUE THREAD

**Issue by coltnz** [thvardhan/Gradianto#6]
Thanks for the theme I love it. I've just got one issue that my OCD just cant let go, believe me I've tried.

When using the find anything popup, the foreground selection color is too dark [as in the highlighted "Aba" below] and makes it hard to read. Any chance of changing this or at least telling me what theme property controls this I've tried to find it with no success..

<img width="696" alt="Screen Shot 2019-08-07 at 10 05 00 AM" src="https://user-images.githubusercontent.com/99617/62580656-dc5e1980-b8fa-11e9-83af-c6eadc9468ba.png">

**Comment by coltnz** [comment]
That's Midnight Blue of course.

**Comment by thvardhan** [comment]
sure I'll give that a go and see what I can come up with

**Comment by thvardhan** [comment]
I've done some workaround as it seems that we can't change the black search text. I hope it will be okay. The update will be live on JetBrains within a few days so keep an eye out for that. you can reopen this thread if there is any problem with the new color or just make a new one.

**Comment by coltnz** [comment]
Thx for that all good now!
