### ISSUE TITLE
Dark Fuchsia does not show visual guides (Code Style)

### ISSUE THREAD

**Issue by schakalakka** [thvardhan/Gradianto#8]
The dark Fuchsia theme does not show the visual guides, i.e. the hard wrap margin line (which is typically set at column 80 oder 120).

The other two themes show the visual guides properly.

**Comment by thvardhan** [comment]
I'll look into it and let you know :O thanks for the report!

**Comment by schakalakka** [comment]
The RIGHT_MARGIN_COLOR is not properly set in the Gradianto_dark_fuchsia.xml
Setting it to a suitable color should fix it.

**Comment by thvardhan** [comment]
fixed in 3.7. The update should go live in 3-4 days and should show in the IntelliJ plugin window. Thanks for the report!
